version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /grpc
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
